#!/bin/bash

export AUTO_REPLY_CONSUMER_TOPIC=AutoReplyConsumerTopic
export AUTO_REPLY_PRODUCER_TOPIC=AutoReplyProducerTopic
export KAFKA_BROKERS=localhost:9092
export DATABASE_HOST=localhost
export DATABASE_PORT=5432
export DATABASE_USER=postgres
export DATABASE_PASSWORD=password
export DATABASE_NAME=auto_reply_db