apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: auto-reply
spec:
  replicas: 1
  serviceName: "auto-reply"
  selector:
    matchLabels:
      app: auto-reply
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: auto-reply
    spec:
      initContainers:
        - name: migrations-container
          image: dm874/auto-reply-migrations:latest
          imagePullPolicy: Always
          envFrom:
            - secretRef:
                name: db-secrets
      containers:
        - name: auto-reply-container
          image: dm874/auto-reply:latest
          imagePullPolicy: Always
          env:
            - name: ROUTER_CONSUMER_TOPIC
              valueFrom:
                configMapKeyRef:
                  name: router-config
                  key: ROUTE_MESSAGE_TOPIC
          envFrom:
            - secretRef:
                name: db-secrets
            - configMapRef:
                name: auto-reply-config
          resources:
            requests:
              memory: "500Mi"
              cpu: "500m"
            limits:
              memory: "1Gi"
              cpu: "1000m"
